#1. SQLite & SQL Querying with Python
In this notebook our goals are to:
- Connect to a SQLite database (using the Sakila database)
- List all tables in the database
- Retrieve column names from the 'customer' table using PRAGMA
- Execute basic SQL queries to explore and filter data

These notes will help you understand how to interact with SQL using Python.

In [4]:
#2. Sakila DB Connection

import sqlite3
import pandas as pd

# Set the path to the SQLite database
db_path = "sakila-1.db"

# Connect to SQLite database
conn = sqlite3.connect(db_path)
print("Connected to SQLite Sakila database!")

Connected to SQLite Sakila database!

##3. List all tables in the database
Here we query the 'sqlite_master' table, which holds the schema info inside of the .db file.

In [5]:
# List all tables in the database
tables = pd.read_sql("""SELECT name
                        FROM sqlite_master
                        WHERE type='table';""", conn)

print("Tables in the database:")
print(tables)

Tables in the database:
               name
0             actor
1           country
2              city
3           address
4          language
5          category
6          customer
7              film
8        film_actor
9     film_category
10        film_text
11        inventory
12            staff
13            store
14          payment
15           rental
16        customers
17  sqlite_sequence
18       test_table

##4. Retrieve column names from the 'customer' table using PRAGMA table_info.
- SQLite allows you to inspect table schema with the PRAGMA command.
- For SQLite 3.16 or later, you can query it like a table.

In [6]:
query_sort = """SELECT name
                FROM pragma_table_info('customer');"""

df_sort = pd.read_sql(query_sort, conn)
print("\nCustomer Table Columns:")
print(df_sort)

Customer Table Columns:
          name
0  customer_id
1     store_id
2   first_name
3    last_name
4        email
5   address_id
6       active
7  create_date
8  last_update

##5. Basic SELECT: Retrieve all customer data
This query selects all columns and rows from the 'customer' table.

# SQL Basics Cheat Sheet [PDF](https://learnsql.com/blog/sql-basics-cheat-sheet/sql-basics-cheat-sheet-letter.pdf)

In [ ]:
#This query selects all columns and rows from the 'customer' table.
query = "SELECT * FROM customer"
df = pd.read_sql_query(query, conn)
df

#explain this 
#

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41

##6. Filtering data: Retrieve only active customers.
- The WHERE clause filters records where the 'active' column equals 1.

In [8]:
#Filtering data: Retrieve only active customers. The WHERE clause filters records where the 'active' column equals 1
query = "SELECT * FROM customer WHERE active = 1"
df = pd.read_sql_query(query, conn)
df

,customer_id,store_id,first_name,last_name,email,address_id,active,create_date,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,1,2006-02-14 22:04:36.000,2021-03-06 15:53:36
...,...,...,...,...,...,...,...,...,...
579,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
580,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
581,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
582,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41
583,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,1,2006-02-14 22:04:37.000,2021-03-06 15:53:41

##7. Sorting data: Order customers by the last_update field in descending order.
- Sorting is useful to see the most recent updates first.
- Only show the first 10 entries.

In [ ]:
query = "SELECT * FROM CUSTOMER"

##8. Group Exercises
- Find a neighbor, yes, move around and make a new friend!
- Work through the following practice exercises together.

## A. Explore the actor Table
- 1. Write a query to display all columns for every actor in the actor table.

- 2. Show only the actor_id, first_name, and last_name columns, and sort by last_name in ascending order.

In [14]:
# A. Explore the actor Table 1. Write a query to display all columns for every actor in the actor table. 2. Show only the actor_id, first_name, and last_name columns, and sort by last_name in ascending order.

query = "SELECT actor_id, first_name, last_name FROM actor ORDER BY last_name ASC"
df = pd.read_sql_query(query, conn)

df

     actor_id first_name  last_name
0          58  CHRISTIAN     AKROYD
1          92    KIRSTEN     AKROYD
2         182     DEBBIE     AKROYD
3         118       CUBA      ALLEN
4         145        KIM      ALLEN
..        ...        ...        ...
195       156        FAY       WOOD
196        63    CAMERON       WRAY
197        85     MINNIE  ZELLWEGER
198       111    CAMERON  ZELLWEGER
199       186      JULIA  ZELLWEGER

[200 rows x 3 columns]

## B. Filter and Sort Data in the film Table
1. Films with a Specific Rating
- Return the film_id, title, and rating of all films where rating = 'PG'.
- Bonus: Are there films "greater than (>)" 'PG'?

2. Films with Rental Rate Above 2.99
- Display the film_id, title, rental_rate, and length for films where the rental_rate is greater than 2.99. Sort them by the shortest length to longest.

3. Longest Films
- List the top 15 longest films (by length), showing title and length. Sort them from longest to shortest.

In [17]:
query = "SELECT film_id, title, rating FROM film WHERE rating = 'PG-13' or rating = 'R'"
df = pd.read_sql_query(query, conn)
df

     film_id               title rating
0          7     AIRPLANE SIERRA  PG-13
1          8     AIRPORT POLLOCK      R
2          9       ALABAMA DEVIL  PG-13
3         17          ALONE TRIP      R
4         18       ALTER VICTORY  PG-13
..       ...                 ...    ...
413      990  WORLD LEATHERNECKS  PG-13
414      993      WRONG BEHAVIOR  PG-13
415      994       WYOMING STORM  PG-13
416      995         YENTL IDAHO      R
417      999   ZOOLANDER FICTION      R

[418 rows x 3 columns]

In [19]:

query = "SELECT film_id, title, rental_rate, length FROM film WHERE rental_rate > 2.99 ORDER BY length ASC"
df = pd.read_sql_query(query, conn)
df

     film_id                title  rental_rate  length
0        469            IRON MOON         4.99      46
1        398       HANOVER GALAXY         4.99      47
2          2       ACE GOLDFINGER         4.99      48
3        575  MIDSUMMER GROUNDHOG         4.99      48
4        670     PELICAN COMFORTS         4.99      48
..       ...                  ...          ...     ...
331      141        CHICAGO NORTH         4.99     185
332      182       CONTROL ANTHEM         4.99     185
333      212       DARN FORRESTER         4.99     185
334      426            HOME PITY         4.99     185
335      817   SOLDIERS EVOLUTION         4.99     185

[336 rows x 4 columns]

In [20]:

query = "SELECT title, length FROM film ORDER BY length DESC LIMIT 15"
df = pd.read_sql_query(query, conn)
df

                 title  length
0        CHICAGO NORTH     185
1       CONTROL ANTHEM     185
2       DARN FORRESTER     185
3          GANGS PRIDE     185
4            HOME PITY     185
5        MUSCLE BRIGHT     185
6         POND SEATTLE     185
7   SOLDIERS EVOLUTION     185
8    SWEET BROTHERHOOD     185
9         WORST BANGER     185
10   CONSPIRACY SPIRIT     184
11    CRYSTAL BREAKING     184
12      KING EVOLUTION     184
13     MOONWALKER FOOL     184
14     SMOOCHY CONTROL     184

##9. Close the connection to the database.
Always close the connection when you're done to free up resources.

In [ ]:
# Close the connection
conn.close()